# Background (solid color)
background {
    monitor =
    color = rgba(000000ff)
}

# General
general {
    no_fade_in = true
    grace = 0
    disable_loading_bar = true
}

# Password input
input-field {
    monitor =
    size = 200, 40
    outline_thickness = 2
    outer_color = rgba(ffffffff)
    inner_color = rgba(000000ff)
    font_color = rgba(ffffffff)

    dots_center = true
    fade_on_empty = true
    rounding = 5

    position = 0, -50
    halign = center
    valign = center
}

# Clock
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 48
    font_color = rgba(ffffffff)

    position = 0, 50
    halign = center
    valign = center
}
